# Generated by Django 3.2.5 on 2021-08-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='question_text',
            new_name='event',
        ),
    ]
